SteveDoyle2/pyNastran

pyNastran/bdf/cards/elements/bars.py

The `CBAR.nodes` attribute was always `None`, even after reading the bdf with `bdf.read_bdf(filename)`.
Some impacts on this issue:
- methods `CBAR.nodePositions`, `CBAR.get_node_positions` etc wouldn't work

BUG: `CBAR.nodes` parameter was returning `None`

---

pyNastran/bdf/cards/elements/bars.py
pyNastran/bdf/cards/elements/rods.py
pyNastran/bdf/cards/elements/shell.py

I've seen the importance of an Edge object such as:
class Edge(object):
def __init__(self):
self.nodes = set()
self.elements = set()
to check the connectivity among elements in an algorithm like:
mesh.edges = []
for element in mesh.elements.values():
el_edges = element.get_edges()
for nodes in el_edges:
nodes = set(nodes)
is_new_edge = True
for edge in mesh.edges:
if nodes == edge.nodes:
is_new_edge = False
break
if is_new_edge:
new_edge = Edge()
new_edge.nodes = set(nodes)
new_edge.elements.add(element)
mesh.edges.append(new_edge)
else:
edge.elements.add(element)
But for this approach to work the `LineElement` and `RodElement` should also have the method `get_edges` implemented, which is conceptually correct.
In this pull request I'm suggesting to add such methods.
If there is interest …

ENH: get_edges for LineElements and RodElement

---

pyNastran/bdf/bdfInterface/getCard.py

There is a nice option to get a node id -> element ids mapping dictionary, but there was no option to get the element objects. This pull request proposes to add such option as default in pyNastran.
Some small improvements in the variable names were also done.

ENH: new mapping option

---

pyNastran/bdf/cards/materials.py

Hello,
BDF reader fails if nu12 is omited in bdf file (generated by MSC.Patran). MSC Nastran documentation tells that nu12 is oprional parameter for MAT8 card definition.
It is proposed to introduce default dummy value to prevent failure of BDF reader.
Example of failed bdf MAT8 entries:
$ Material Record : mat8.4
$ Description of Material :
MAT8     4      10.     10.             2700.   2700.   2700.
$ Material Record : mat8.5
$ Description of Material :
MAT8     5      10.     10.             2700.   2700.   2700.
$ Material Record : mat8.6
$ Description of Material :
MAT8     6      100.    100.            2700.   2700.   2700.
$ Material Record : mat8.8
$ Description of Material :
MAT8     8      7200.   7200.           2700.   2700.   2700.
Proposed change was tested successfully.

Set default nu12 property for MAT8 card parser

---

pyNastran/bdf/cards/elements/bars.py
pyNastran/bdf/cards/elements/beam.py

I was playing around with models mixing both shell and bar elements and got the following error when running `get_node_positions()`:
File "C:\repos\pyNastran\pyNastran\bdf\cards\base_card.py", line 369, in get_node_positions
nnodes = len(self.nodes_ref)
AttributeError: 'CBAR' object has no attribute 'nodes_ref'
I believe the current pull request can fix this.

BUG: get_node_positions() would'n work for bars and beam

---

pyNastran/op2/data_in_material_coord.py

- small bug fix
- would throw an error if the bdf contained any element without `thetaMcid`, or an element which property did not contain `t`

BUG: supporting models with elements other than only 2D shells

---

pyNastran/op2/tables/oes_stressStrain/real/oes_springs.py

Variables `ntimes` and `nelements` were not in context

BUG: small fix

---

pyNastran/converters/nastran/nastranIOv.py
pyNastran/gui/gui_common.py
pyNastran/gui/menus/manage_actors.py

GUI
----
* Fixed the 'Show/Hide CAERO Panels', 'Toggle CAERO Subpanels', and 'Toggle CONM2s' button behavior in relation to the Edit Geometry Properties dialog.
* Added ``GuiCommon2.on_update_geometry_properties_override_dialog`` to update properties even when the dialog is open.
* Removed redundant calls to set the previous object properties in ``EditGeometryProperties.update_active_key``

Fix for CAERO Buttons (Finally)

---

pyNastran/bdf/subcase.py

Control decks with a lot of subcases are slow to read, due to deepcopying of previously defined subcases.  A __deepcopy__ method has been added to the Subcase class to override the default copy.deepcopy method.  This method is at least 2x faster, although ideally it would be an order of magnitude faster.

speed up Subcase deepcopy

---

pyNastran/bdf/subcase.py
pyNastran/bdf/test/test_case_control_deck.py

When the default subcase is copied for every subcase that is defined, all SET definitions were previously deep copied.  If these sets were large, this would be very slow.  Now the default subcase is shallow copied, and the bdf read time is greatly improved.  A unit test has also been added to confirm that it is working as desired.

default subcase now shallow copied

---

pyNastran/bdf/cards/elements/elements.py

The code was previously setting cid to 0 if blank when x1_g0 is a float.  This will always override the cgap x-axis if the user wishes to use the ga to gb vector for its x-axis where ga and gb are not coincident (in which case cid would be blank).  This causes incorrect results.

fixes #493 - CBUSH cid default

---

pyNastran/bdf/bdf.py

The bdf reader doesn't parse headers for StringIO buffers passed in the 'read_bdf' method.  Small changes were made to parse the headers the StringIO objects.  After the 'readlines' method is called on the StringIO object, it is rewound using seek(0) to go back to the beginning so that the lines can be read again in the '_get_main_lines' method.

bdf reader: StringIO parse headers

---

pyNastran/op2/op2_interface/op2_common.py

The attributes `self._endian` and `self_analysis_code_fmt` are bytes so an exception is thrown because of concatenating a byte with a string.

Changing string to byte literal in Struct format

---

pyNastran/bdf/cards/properties/bars.py

Missing two squares in the corners while calculating the area.

Fixed pbarl 'CHAN' Area calculation

---

pyNastran/utils/atmosphere.py

Add cm/s units to atmospheric units, specifically the _velocity_factor method.  An issue was found when plotting flutter VG diagrams when the model was in units of cm's.

Add cm/s units to _velocity_factor method.

---

pyNastran/bdf/cards/loads/dloads.py

Fixing bug in TLOAD2 get_load_at_time method which was setting both frequency and force vector to the same variable

Fixing bug in TLOAD2 get_load_at_time method

---

pyNastran/op2/op2_interface/op2_f06_common.py

The CHEXA composite stresses were not set by its setter because the setter took no arguments. Additionally, the setter referred to the wrong variable to set (chexa_stress instead of chexa_composite_stress).

CHEXA composite stress now correctly set by @setter in OP2 results.

---

pyNastran/bdf/cards/contact.py

The BGSET card format looks like this:
Therefore, EXTj should be read from fields i+4 with i=2+10*(j-1), instead of the current i+3 and i=2+8*(j-1).

Bugfix: BDF, BGSET card field reading

---

pyNastran/bdf/bdf.py
pyNastran/bdf/bdf_interface/add_card.py
pyNastran/bdf/bdf_interface/add_methods.py
pyNastran/bdf/bdf_interface/attributes.py
pyNastran/bdf/bdf_interface/stats.py
pyNastran/bdf/bdf_interface/write_mesh.py
pyNastran/bdf/cards/coordinate_systems.py
pyNastran/bdf/cards/test/test_coords.py

Added reading / writing of MATCID cards to the BDF.
Multiple cards can share the same CID. Therefore, I tried to use the same approach as for load cards (e.g., PLOAD4), i.e., the MATCID cards are stored as a dict whose keys are the unique CIDs and whose values are lists containing the MATCID cards referencing that CID:
{cid1: List[matcid1, matcid2, ...], cid2: List[matcidN1, matcidN2, ...], ...}
I also tried to add a small unit test to check that the cards are correctly read and stored.

Add matcid card to bdf

---

pyNastran/bdf/__init__.py
pyNastran/bdf/bdf.py
pyNastran/bdf/bdf_interface/add_card.py
pyNastran/bdf/bdf_interface/add_methods.py
pyNastran/bdf/bdf_interface/attributes.py
pyNastran/bdf/bdf_interface/card_groups.py
pyNastran/bdf/bdf_interface/stats.py
pyNastran/bdf/cards/elements/elements.py
pyNastran/bdf/cards/properties/properties.py

There exists five different formats of CWELD card in MSC Nastran. In this PR, three most common used formats are supported: PARTRAT, ELPAT, ELEMID.

Support cweld and pweld card for MSC Nastran
