SteveDoyle2/pyNastran

- pyNastran/bdf/bdfInterface/crossReference.py
- this commit will allow to get not only `bdf.elements[eid].nodes` but also `bdf.nodes[nid].elements`
> ENH: added cross reference node->elements

- pyNastran/bdf/cards/aero.py
- pyNastran/converters/nastran/nastranIOv.py
- pyNastran/gui/gui_common.py
Added
----------
* CAERO1.box_ids
* AESURF actor
* Default color dictionary
To Do
---------
More cleanup
Toggle function for AESURF actor
More generalized gui actor object
> More Nastran gui enhancements

- pyNastran/bdf/cards/properties/beam.py
- pyNastran/converters/nastran/nastranIOv.py
- pyNastran/gui/gui_common.py
Gui
------
Fixed CONMs to use new alternate actor/grid scheme
CONMs appear using point representation
Added magnification override for on_take_screenshot
Removed a lot of references to old grid2
Re-added --geomscript functionality (not sure how it got removed)
Bdf
----
Added long error message for PBEAM card. This should help figure out what is happening when you have blank lines.
> Various gui updates

- pyNastran/gui/arg_handling.py
- pyNastran/gui/gui_common.py
GUI
------
* Added linewidth scaling to screenshots 
* Removed corner axis from screenshots
* Set default screenshot magnification to 5x
> GUI Screenshot updates

- pyNastran/op2/data_in_material_coord.py
- pyNastran/op2/test/test_op2_in_material_coord.py
Thanks @SteveDoyle2  it was really a bug with the strain_xy/2
> BUG: fixed strain convertion to material coord

- pyNastran/op2/data_in_material_coord.py
Improved documentation for the new function.
Still don't know how to merge with the main documentation for op2.
> DOC: improved documentation

- pyNastran/bdf/bdf.py
- pyNastran/converters/nastran/nastranIOv.py
- pyNastran/gui/qt_version.py
Fix for gui for models with Spoints or Epoints
> Fix for gui for models with SPoints or Epoints

- pyNastran/bdf/cards/elements/beam.py
- pyNastran/bdf/mesh_utils/find_closest_nodes.py
- pyNastran/converters/nastran/nastranIOv.py
Fixed bug with CBEAM property is_offt.
Fixed bug in find_closest_nodes and updated documentation.
Fixed bug in gui where mpc alternate geometries of RBEs wouldn't show.
> Minor Bug Fixes

- pyNastran/xdb/xdb.py
XDB data blocks control information.
> Comments on XDB data control information

- pyNastran/xdb/xdb.py
- pyNastran/xdb/xdb_object.py
Added XDB_obj class for handling XDB table header information.
> XDB_obj class for handling XDB table header information

- pyNastran/xdb/enums.py
- pyNastran/xdb/xdb_object.py
XDB solution code to textual representation mapping via enumeration.
> XDB solution code to textual representation mapping

- pyNastran/xdb/xdb.py
SUBGRID offset value correction + bugfixing.
> SUBGRID offset value correction

- pyNastran/bdf/bdf.py
- pyNastran/converters/nastran/nastranIOv.py
> Fix for spoints in gui

- pyNastran/gui/gui.py
* Added a gui fix that shows the correct icon in the Windows taskbar.
> Added a gui fix that shows the correct icon in the Windows taskbar.

- pyNastran/bdf/subcase.py
added some documentation for Subcase.__deepcopy__ method
> Subcase.__deepcopy__ documentation

- models/bar3truss/dynamic_syntax.py
This piece of code doesn't work anymore due to OP2 is vectorized by default.
> Demo problems update

- setup_no_gui.py
Indent was missing for numpy py_packages append in the if statement.
> Minor fix to setup_no_gui

- h5Nastran/h5Nastran/input/property.py
some will need custom implementations
> h5Nastran - added place holders for all property cards

- pyNastran/op2/dev/op2.py
fixes exception when reading op2 file
> op2 endian should be bytes not unicode

- h5Nastran/h5Nastran/post_process/result_readers/op2/op2_to_h5.py
- h5Nastran/h5Nastran/post_process/result_readers/op2/test2.py
> h5Nastran: example cleanup

- pyNastran/op2/op2_interface/op2_reader.py
Tested and working on Optistruct 2019.2
> Add Optistruct 2019.2 support

- docs/html_docs/installation/building_docs.rst
- requirements.txt
Just a minor update of the documentation adding relevant modules and specifying installation with `develop` instead of `install`, as discussed in Issue #654
> Issue 654 installation

- pyNastran/bdf/bdf.py
- pyNastran/bdf/bdf_interface/add_card.py
- pyNastran/bdf/bdf_interface/add_methods.py
- pyNastran/bdf/bdf_interface/attributes.py
- pyNastran/bdf/bdf_interface/stats.py
- pyNastran/bdf/bdf_interface/write_mesh.py
- pyNastran/bdf/cards/material_deps.py
- pyNastran/bdf/cards/test/test_materials.py
I also tried adding a small unit test to verify the new code. It was also tested manually with a .dat file created with Simcenter Nastran.
> Add MATDMG card reading/writing capability to BDF
